
version: 1.0.0.{build}.{branch}
    
before_build:
 - cmd: dotnet restore AspNetCoreGettingStarted.sln

build_script:
 - cmd: dotnet build src\AspNetCoreGettingStarted
 - cmd: dotnet publish src\AspNetCoreGettingStarted
