version: 1.0.0.{build}.{branch}
image: Visual Studio 2017    
before_build:
 - cmd: dotnet restore AspNetCoreGettingStarted.sln
build_script:
 - cmd: dotnet build src\AspNetCoreGettingStarted
 - cmd: dotnet publish src\AspNetCoreGettingStarted
